
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: booksdump
  name: booksdump
  namespace: booksdump
spec:
  selector:
    matchLabels:
      app: booksdump
  template:
    metadata:
      labels:
        app: booksdump
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: booksdump
          image: aladex/gopds-frontend:v0.0.19
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http-booksdump
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /index.html
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - name: books-posters
              mountPath: /books/
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: books-posters
          persistentVolumeClaim:
            claimName: pvc-posters
        - name: nginx-config
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: booksdump
  namespace: booksdump
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-booksdump
  selector:
    app: booksdump
  sessionAffinity: None
  type: ClusterIP

