---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: booksdump
data:
  nginx.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri /index.html;
        }
        location /books-posters {
        alias /books/;
        }
    }
