name: ci

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NODE_ENV=production
            VUE_APP_BACKEND_API_URL=https://booksdump.com/
            VUE_APP_CDN_URL=https://cdn.booksdump.com/
            VUE_APP_ONPAGE=10
          push: true
          tags: aladex/gopds-frontend:${{ steps.get_version.outputs.VERSION }}
      - name: Build and push beta
        id: docker_build_beta
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NODE_ENV=beta
            VUE_APP_BACKEND_API_URL=https://beta.booksdump.com/
            VUE_APP_CDN_URL=https://beta.booksdump.com/
            VUE_APP_ONPAGE=10
          push: true
          tags: aladex/gopds-frontend-beta:${{ steps.get_version.outputs.VERSION }}
